import React from "react";

export default function About() {
  return (
    <div className="wrapper test h-screen">
      <div className="container mx-auto lg:px-32 py-8">
        <p className=" text-red-800 text-center">
          Note: The information provided is not real and has been generated by
          an AI.
        </p>
        <h2 className="text-3xl font-bold mb-4 text-center">About Kathrence</h2>
        <div className="mb-8">
          <h3 className="text-xl font-bold mb-2">Mission</h3>
          <p className="mb-4">
            Our mission at Kathrence is simple: to provide cat owners with
            convenient, effective, and environmentally friendly litter solutions
            that enhance the well-being of both cats and their owners. We strive
            to continuously innovate and improve our products to ensure the
            highest standards of quality and satisfaction.
          </p>
        </div>
        <div className="mb-8">
          <h3 className="text-xl font-bold mb-2">Vision</h3>
          <p className="mb-4">
            Our vision is to be the leading provider of cat litter solutions
            globally, recognized for our commitment to excellence, innovation,
            and sustainability. We aim to enrich the lives of cats and their
            owners by offering products that promote health, hygiene, and
            harmony in homes.
          </p>
        </div>
        <div className="mb-8">
          <h3 className="text-xl font-bold mb-2">Why Choose Us?</h3>
          <p className="mb-4">
            <strong>Quality Assurance:</strong> We source our materials from
            trusted suppliers and conduct rigorous quality control checks to
            ensure that every product meets our stringent standards.
          </p>
          <p className="mb-4">
            <strong>Variety:</strong> With a diverse selection of litter types
            and formulations, Kathrence caters to the unique preferences and
            needs of every cat and owner.
          </p>
          <p className="mb-4">
            <strong>Environmental Responsibility:</strong> We're committed to
            sustainability and offer eco-friendly litter options that minimize
            environmental impact without compromising performance.
          </p>
          <p className="mb-4">
            <strong>Customer Satisfaction:</strong> At Kathrence, customer
            satisfaction is our top priority. We're dedicated to providing
            exceptional service and support to ensure that every customer has a
            positive experience.
          </p>
        </div>
      </div>
    </div>
  );
}
