import React from "react";

export default function Contact() {
  return (
    <div className="wrapper test h-screen">
      <div className="container mx-auto lg:px-32 py-8">
        <p className=" text-red-800 text-center">
          Note: The information provided is not real and has been generated by
          an AI.
        </p>
        <h2 className="text-3xl font-bold mb-4">Contact Us</h2>
        <p className="mb-4">
          Located at 2991 Kaalinsabay St., Karangalan Village, Manggahan, Pasig
          City, Kathrence is conveniently situated to serve cat owners in the
          surrounding area. Have questions or need assistance? Our friendly and
          knowledgeable team is here to help! Reach out to us via phone at{" "}
          <strong>[insert phone number]</strong> or email at{" "}
          <strong>[insert email address]</strong>.
        </p>
        {/* Add a contact form or additional contact information here */}
      </div>
    </div>
  );
}
